---
title: "Content"
output:
  bookdown::html_document2:
    toc: false
    number_sections: false
---

```{r,child="assets/header-lab.Rmd"}
```

This page contains links to different lectures (slides) and practical exercises (labs) that are part of this workshop. The links below are similar to that under [Schedule](home_schedule.html) but organised here by topic.

<br>

<div class="boxy boxy-lightbulb">
Input code blocks are displayed like shown below. The code language is displayed above the block. Shell scripts (**SH**) are to be executed in the linux terminal. **R** scripts are to be run in R either through the terminal, RGui or RStudio.

```{sh,eval=FALSE,chunk.title=TRUE}
command
```

<i class="fas fa-exclamation-circle"></i> Note &nbsp; <i class="fas fa-lightbulb"></i> Tip &nbsp; <i class="fas fa-comments"></i> Discuss &nbsp; <i class="fas fa-clipboard-list"></i> Task
</div>

<br>

# Pre-Reads

1.  [Introduction to Bioinformatics](preread_introduction.html)
2.  [Software Installation](preread_software.html)
3.  [Next-Generation Sequencing](preread_sequencing.pdf)
4.  [Data Sources](preread_sources.html)
5.  [Data Formats](preread_formats.html)
6.  [Data Visualization](preread_visualization.html)
7.  [Quality Control](preread_quality.html)
8.  [Sequence Alignment](preread_alignment.html)
9.  [Read Mapping](preread_mapping.html)
10. [SAM Format](preread_sam.html)
11. [RNA-seq](preread_rnaseq.html)
12. [Metagenomics](preread_metagenomics.pdf)
13. [Microarray](preread_microarray.html)
14. [Epidemiology](preread_epidemiology.html)
15. [Genomic Variations](preread_genomicvariation.html)

# Slides

1.  [Introduction to Bioinformatics](slide_introduction.html)
2.  [Software Installation](slide_software.html)
3.  [Next-Generation Sequencing](slide_sequencing.html)
4.  [Data Sources](slide_sources.html)
5.  [Data Formats](slide_formats.html)
6.  [Data Visualization](slide_visualization.html)
7.  [Quality Control](slide_quality.html)
8.  [Sequence Alignment](slide_alignment.html)
9.  [Read Mapping](slide_mapping.html)
10. [SAM Format](slide_sam.html)
11. [RNA-seq](slide_rnaseq.html)
12. [Metagenomics](slide_microbiome.html)
13. [Microarray](slide_microarray.html)
14. [Epidemiology](slide_epidemiology.html)
15. [Genomic Variation](slide_genvar.html)

# Labs

1. [Software Installation-Conda](lab_software.html)
2. [NGS- SRA Toolkit and EDirect](lab_sequencing.html)
3. [Data Formats- FASTA/Q Processing](lab_formats.html)
4. [Data Visualization-IGV](lab_visualization.html)
5. [Quality Control](lab_quality.html)
6. [Read mapping](lab_mapping.html)
7. [SAM Format- Samtools](lab_sam.html)
8. [Analysis of RNA-seq data](lab_rnaseq.html)
9. [Microarray analysis](lab_microarray.html)

***
