library(rmarkdown)

render("slide_introduction.Rmd", "xaringan::moon_reader")
render("slide_software.Rmd", "xaringan::moon_reader")
#render("slide_sequencing.Rmd", "xaringan::moon_reader") 
render("slide_sources.Rmd", "xaringan::moon_reader")
render("slide_formats.Rmd", "xaringan::moon_reader")
render("slide_visualization.Rmd", "xaringan::moon_reader")
render("slide_quality.Rmd", "xaringan::moon_reader")
render("slide_alignment.Rmd", "xaringan::moon_reader")
render("slide_mapping.Rmd", "xaringan::moon_reader")
render("slide_sam.Rmd", "xaringan::moon_reader")

render("lab_software.Rmd")
render("lab_sequencing.Rmd")
render("lab_formats.Rmd")
render("lab_visualization.Rmd")
render("lab_quality.Rmd")
render("lab_mapping.Rmd")
render("lab_sam.Rmd")
render("lab_rnaseq.Rmd")